export enum Race {
    ASIAN = "Asian",
    BLACK = "Black",
    NATIVE_AMERICAN = "Native American",
    PACIFIC_ISLANDER = "Pacific Islander",
    HISPANIC = "Hispanic",
    WHITE = "White",
    OTHERS = "Others",
    NOT_DISCLOSED = "Not Disclosed",
  }
  
  export enum Gender {
    MALE = "Male",
    FEMALE = "Female",
    REGULAR = "Gender other than male or female",
    NOT_DISCLOSED = "Not Disclosed",
  }
  
  export enum Ranking {
    TOP1 = "Top 1%",
    TOP5 = "Top 5%",
    TOP10 = "Top 10%",
    TOP15 = "Top 15%",
    TOP20 = "Top 20%",
    TOP25 = "Top 25%",
    TOP50 = "Top 50%",
    BOTTOM50 = "Bottom 50%",
    NOT_DISCLOSED = "Not Disclosed",
  }

  export enum Residency_Status {
    Citizen = "U.S. Citizen",
    Permanent = "Permanent Resident",
    International = "International Student on Visa"
  }

  export enum Resident_State {
    Alabama = "Alabama",
    Alaska = "Alaska",
    Arizona = "Arizona",
    Arkansas = "Arkansas",
    California = "California",
    Colorado = "Colorado",
    Connecticut = "Connecticut",
    Delaware = "Delaware",
    Florida = "Florida",
    Georgia = "Georgia",
    Hawaii = "Hawaii",
    Idaho = "Idaho",
    Illinois = "Illinois",
    Indiana = "Indiana",
    Iowa = "Iowa",
    Kansas = "Kansas",
    Kentucky = "Kentucky",
    Louisiana = "Louisiana",
    Maine = "Maine",
    Maryland = "Maryland",
    Massachusetts = "Massachusetts",
    Michigan = "Michigan",
    Minnesota = "Minnesota",
    Mississippi = "Mississippi",
    Missouri = "Missouri",
    Montana = "Montana",
    Nebraska = "Nebraska",
    Nevada = "Nevada",
    New_Hampshire = "New Hampshire",
    New_Jersey = "New Jersey",
    New_Mexico = "New Mexico",
    New_York = "New York",
    North_Carolina = "North Carolina",
    North_Dakota = "North Dakota",
    Ohio = "Ohio",
    Oklahoma = "Oklahoma",
    Oregon = "Oregon",
    Oversea = "Oversea",
    Pennsylvania = "Pennsylvania",
    Rhode_Island = "Rhode Island",
    South_Carolina = "South Carolina",
    South_Dakota = "South Dakota",
    Tennessee = "Tennessee",
    Texas = "Texas",
    Utah = "Utah",
    Vermont = "Vermont",
    Virginia = "Virginia",
    Washington = "Washington",
    West_Virginia = "West Virginia",
    Wisconsin = "Wisconsin",
    Wyoming = "Wyoming",
  }
  