import { LocationURLCombined } from "./map-data-types";

export const locationMap: Map<string, LocationURLCombined> = new Map([
    ["Princeton University", { loc: { latitude: 40.3430, longitude: -74.6514 }, url: new URL("https://www.princeton.edu/") }],
    ["Massachusetts Institute of Technology (MIT)", { loc: { latitude: 42.3601, longitude: -71.0942 }, url: new URL("https://www.mit.edu/") }],
    ["Harvard University", { loc: { latitude: 42.3770, longitude: -71.1167 }, url: new URL("https://www.harvard.edu/") }],
    ["Stanford University", { loc: { latitude: 37.4275, longitude: -122.1697 }, url: new URL("https://www.stanford.edu/") }],
    ["Yale University", { loc: { latitude: 41.3163, longitude: -72.9223 }, url: new URL("https://www.yale.edu/") }],
    ["University of Chicago", { loc: { latitude: 41.7886, longitude: -87.5987 }, url: new URL("https://www.uchicago.edu/") }],
    ["Johns Hopkins University", { loc: { latitude: 39.3299, longitude: -76.6205 }, url: new URL("https://www.jhu.edu/") }],
    ["University of Pennsylvania", { loc: { latitude: 39.9522, longitude: -75.1932 }, url: new URL("https://www.upenn.edu/") }],
    ["California Institute of Technology", { loc: { latitude: 34.1377, longitude: -118.1253 }, url: new URL("https://www.caltech.edu/") }],
    ["Duke University", { loc: { latitude: 36.0014, longitude: -78.9382 }, url: new URL("https://www.duke.edu/") }],
    ["Northwestern University", { loc: { latitude: 42.0565, longitude: -87.6753 }, url: new URL("https://www.northwestern.edu/") }],
    ["Dartmouth College", { loc: { latitude: 43.7044, longitude: -72.2887 }, url: new URL("https://home.dartmouth.edu/") }],
    ["Brown University", { loc: { latitude: 41.8268, longitude: -71.4025 }, url: new URL("https://www.brown.edu/") }],
    ["Vanderbilt University", { loc: { latitude: 36.1447, longitude: -86.8027 }, url: new URL("https://www.vanderbilt.edu/") }],
    ["Rice University", { loc: { latitude: 29.7174, longitude: -95.4018 }, url: new URL("https://www.rice.edu/") }],
    ["Washington University in St. Louis", { loc: { latitude: 38.6488, longitude: -90.3108 }, url: new URL("https://wustl.edu/") }],
    ["Cornell University", { loc: { latitude: 42.4534, longitude: -76.4735 }, url: new URL("https://www.cornell.edu/") }],
    ["University of Notre Dame", { loc: { latitude: 41.7056, longitude: -86.2353 }, url: new URL("https://www.nd.edu/") }],
    ["Emory University", { loc: { latitude: 33.7925, longitude: -84.3240 }, url: new URL("https://www.emory.edu/") }],
    ["Georgetown University", { loc: { latitude: 38.9076, longitude: -77.0723 }, url: new URL("https://www.georgetown.edu/") }],
    ["University of California, Berkeley", { loc: { latitude: 37.8719, longitude: -122.2585 }, url: new URL("https://www.berkeley.edu/") }],
    ["University of Southern California", { loc: { latitude: 34.0224, longitude: -118.2851 }, url: new URL("https://www.usc.edu/") }],
    ["Carnegie Mellon University", { loc: { latitude: 40.4433, longitude: -79.9426 }, url: new URL("https://www.cmu.edu/") }],
    ["University of California, Los Angeles", { loc: { latitude: 34.0689, longitude: -118.4452 }, url: new URL("https://www.ucla.edu/") }],
    ["University of Michigan, Ann Arbor", { loc: { latitude: 42.2780, longitude: -83.7382 }, url: new URL("https://umich.edu/") }],
    ["University of Virginia", { loc: { latitude: 38.0336, longitude: -78.5080 }, url: new URL("https://www.virginia.edu/") }],
    ["Wake Forest University", { loc: { latitude: 36.1350, longitude: -80.2784 }, url: new URL("https://www.wfu.edu/") }],
    ["New York University", { loc: { latitude: 40.7295, longitude: -73.9965 }, url: new URL("https://www.nyu.edu/") }],
    ["Tufts University", { loc: { latitude: 42.4075, longitude: -71.1190 }, url: new URL("https://www.tufts.edu/") }],
    ["University of North Carolina at Chapel Hill", { loc: { latitude: 35.9049, longitude: -79.0469 }, url: new URL("https://www.unc.edu/") }],
    ["University of Rochester", { loc: { latitude: 43.1286, longitude: -77.6285 }, url: new URL("https://www.rochester.edu/") }],
    ["Boston College", { loc: { latitude: 42.3355, longitude: -71.1685 }, url: new URL("https://www.bc.edu/") }],
    ["University of California, Santa Barbara", { loc: { latitude: 34.4139, longitude: -119.8489 }, url: new URL("https://www.ucsb.edu/") }],
    ["University of Florida", { loc: { latitude: 29.6436, longitude: -82.3549 }, url: new URL("https://www.ufl.edu/") }],
    ["University of California, San Diego", { loc: { latitude: 32.8801, longitude: -117.2340 }, url: new URL("https://www.ucsd.edu/") }],
    ["University of California, Irvine", { loc: { latitude: 33.6405, longitude: -117.8443 }, url: new URL("https://www.uci.edu/") }],
    ["University of Texas at Austin", { loc: { latitude: 30.2849, longitude: -97.7341 }, url: new URL("https://www.utexas.edu/") }],
    ["Boston University", { loc: { latitude: 42.3505, longitude: -71.1054 }, url: new URL("https://www.bu.edu/") }],
    ["University of Wisconsin–Madison", { loc: { latitude: 43.0766, longitude: -89.4125 }, url: new URL("https://www.wisc.edu/") }],
    ["University of Illinois Urbana-Champaign", { loc: { latitude: 40.1020, longitude: -88.2272 }, url: new URL("https://illinois.edu/") }],
    ["University of Georgia", { loc: { latitude: 33.9480, longitude: -83.3773 }, url: new URL("https://www.uga.edu/") }],
    ["Ohio State University", { loc: { latitude: 40.0076, longitude: -83.0300 }, url: new URL("https://www.osu.edu/") }],
    ["Pepperdine University", { loc: { latitude: 34.0400, longitude: -118.7070 }, url: new URL("https://www.pepperdine.edu/") }],
    ["Syracuse University", { loc: { latitude: 43.0379, longitude: -76.1349 }, url: new URL("https://www.syracuse.edu/") }],
    ["University of Miami", { loc: { latitude: 25.7174, longitude: -80.2784 }, url: new URL("https://www.miami.edu/") }],
    ["Purdue University", { loc: { latitude: 40.4237, longitude: -86.9212 }, url: new URL("https://www.purdue.edu/") }],
    ["University of Connecticut", { loc: { latitude: 41.8084, longitude: -72.2520 }, url: new URL("https://uconn.edu/") }],
    ["University of Washington", { loc: { latitude: 47.6553, longitude: -122.3035 }, url: new URL("https://www.washington.edu/") }],
    ["University of Maryland, College Park", { loc: { latitude: 38.9869, longitude: -76.9426 }, url: new URL("https://www.umd.edu/") }],
    ["Clemson University", { loc: { latitude: 34.6784, longitude: -82.8374 }, url: new URL("https://www.clemson.edu/") }],
    ["Pennsylvania State University", { loc: { latitude: 40.7982, longitude: -77.8599 }, url: new URL("https://www.psu.edu/") }],
    ["Southern Methodist University", { loc: { latitude: 32.8410, longitude: -96.7845 }, url: new URL("https://www.smu.edu/") }],
    ["Texas A&M University", { loc: { latitude: 30.6150, longitude: -96.3425 }, url: new URL("https://www.tamu.edu/") }],
    ["Fordham University", { loc: { latitude: 40.8612, longitude: -73.8857 }, url: new URL("https://www.fordham.edu/") }],
    ["University of Pittsburgh", { loc: { latitude: 40.4443, longitude: -79.9608 }, url: new URL("https://www.pitt.edu/") }],
    ["American University", { loc: { latitude: 38.9375, longitude: -77.0898 }, url: new URL("https://www.american.edu/") }],
    ["Baylor University", { loc: { latitude: 31.5493, longitude: -97.1143 }, url: new URL("https://www.baylor.edu/") }],
    ["Clark University", { loc: { latitude: 42.2518, longitude: -71.8248 }, url: new URL("https://www.clarku.edu/") }],
    ["Colorado School of Mines", { loc: { latitude: 39.7510, longitude: -105.2226 }, url: new URL("https://www.mines.edu/") }],
    ["Michigan State University", { loc: { latitude: 42.7018, longitude: -84.4822 }, url: new URL("https://msu.edu/") }],
    ["Stevens Institute of Technology", { loc: { latitude: 40.7440, longitude: -74.0253 }, url: new URL("https://www.stevens.edu/") }],
    ["University of Delaware", { loc: { latitude: 39.6780, longitude: -75.7526 }, url: new URL("https://www.udel.edu/") }],
    ["University of Denver", { loc: { latitude: 39.6780, longitude: -104.9610 }, url: new URL("https://www.du.edu/") }],
    ["University of Tulsa", { loc: { latitude: 36.1539, longitude: -95.9450 }, url: new URL("https://utulsa.edu/") }],
    ["Indiana University Bloomington", { loc: { latitude: 39.1653, longitude: -86.5264 }, url: new URL("https://www.indiana.edu/") }],
    ["Marquette University", { loc: { latitude: 43.0389, longitude: -87.9300 }, url: new URL("https://www.marquette.edu/") }],
    ["University of Colorado Boulder", { loc: { latitude: 40.0076, longitude: -105.2659 }, url: new URL("https://www.colorado.edu/") }],
    ["University of Massachusetts Amherst", { loc: { latitude: 42.3868, longitude: -72.5301 }, url: new URL("https://www.umass.edu/") }],
    ["University of Vermont", { loc: { latitude: 44.4759, longitude: -73.2121 }, url: new URL("https://www.uvm.edu/") }],
    ["Worcester Polytechnic Institute", { loc: { latitude: 42.2748, longitude: -71.8063 }, url: new URL("https://www.wpi.edu/") }],
    ["Yeshiva University", { loc: { latitude: 40.8505, longitude: -73.9290 }, url: new URL("https://www.yu.edu/") }],
    ["Binghamton University", { loc: { latitude: 42.0886, longitude: -75.9690 }, url: new URL("https://www.binghamton.edu/") }],
    ["Florida State University", { loc: { latitude: 30.4419, longitude: -84.2985 }, url: new URL("https://www.fsu.edu/") }],
    ["Miami University", { loc: { latitude: 39.5078, longitude: -84.7332 }, url: new URL("https://miamioh.edu/") }],
    ["North Carolina State University", { loc: { latitude: 35.7847, longitude: -78.6821 }, url: new URL("https://www.ncsu.edu/") }],
    ["SUNY College of Environmental Science and Forestry", { loc: { latitude: 43.0347, longitude: -76.1360 }, url: new URL("https://www.esf.edu/") }],
    ["University of Iowa", { loc: { latitude: 41.6611, longitude: -91.5365 }, url: new URL("https://uiowa.edu/") }],
    ["University of Minnesota Twin Cities", { loc: { latitude: 44.9737, longitude: -93.2354 }, url: new URL("https://twin-cities.umn.edu/") }],
    ["University of Missouri", { loc: { latitude: 38.9453, longitude: -92.3280 }, url: new URL("https://missouri.edu/") }],
    ["University of Oklahoma", { loc: { latitude: 35.2072, longitude: -97.4457 }, url: new URL("https://www.ou.edu/") }],
    ["University of Oregon", { loc: { latitude: 44.0448, longitude: -123.0726 }, url: new URL("https://www.uoregon.edu/") }],
    ["University of San Diego", { loc: { latitude: 32.7714, longitude: -117.1880 }, url: new URL("https://www.sandiego.edu/") }],
    ["University of San Francisco", { loc: { latitude: 37.7749, longitude: -122.4194 }, url: new URL("https://www.usfca.edu/") }],
    ["University of South Carolina", { loc: { latitude: 33.9965, longitude: -81.0270 }, url: new URL("https://www.sc.edu/") }],
    ["University of Tennessee", { loc: { latitude: 35.9545, longitude: -83.9295 }, url: new URL("https://www.utk.edu/") }],
    ["University of Utah", { loc: { latitude: 40.7649, longitude: -111.8421 }, url: new URL("https://www.utah.edu/") }],
    ["Villanova University", { loc: { latitude: 40.0374, longitude: -75.3430 }, url: new URL("https://www.villanova.edu/") }],
    ["Virginia Tech", { loc: { latitude: 37.2284, longitude: -80.4234 }, url: new URL("https://www.vt.edu/") }],
    ["Washington and Lee University", { loc: { latitude: 37.7900, longitude: -79.4428 }, url: new URL("https://www.wlu.edu/") }],
    ["Williams College", { loc: { latitude: 42.7128, longitude: -73.2031 }, url: new URL("https://www.williams.edu/") }],
    ["Wellesley College", { loc: { latitude: 42.2936, longitude: -71.3065 }, url: new URL("https://www.wellesley.edu/") }],
    ["Wesleyan University", { loc: { latitude: 41.5565, longitude: -72.6569 }, url: new URL("https://www.wesleyan.edu/") }],
    ["Whitman College", { loc: { latitude: 46.0705, longitude: -118.3302 }, url: new URL("https://www.whitman.edu/") }],
    ["Amherst College", { loc: { latitude: 42.3709, longitude: -72.5169 }, url: new URL("https://www.amherst.edu/") }],
    ["Babson College", { loc: { latitude: 42.2993, longitude: -71.2653 }, url: new URL("https://www.babson.edu/") }],
    ["Barnard College", { loc: { latitude: 40.8090, longitude: -73.9630 }, url: new URL("https://barnard.edu/") }],
    ["Bates College", { loc: { latitude: 44.1052, longitude: -70.2030 }, url: new URL("https://www.bates.edu/") }],
    ["Beloit College", { loc: { latitude: 42.5030, longitude: -89.0300 }, url: new URL("https://www.beloit.edu/") }],
    ["Bennington College", { loc: { latitude: 42.9234, longitude: -73.2460 }, url: new URL("https://www.bennington.edu/") }],
    ["Bentley University", { loc: { latitude: 42.3884, longitude: -71.2200 }, url: new URL("https://www.bentley.edu/") }],
    ["Berea College", { loc: { latitude: 37.5720, longitude: -84.2960 }, url: new URL("https://www.berea.edu/") }],
    ["Bowdoin College", { loc: { latitude: 43.9088, longitude: -69.9631 }, url: new URL("https://www.bowdoin.edu/") }],
    ["Brandeis University", { loc: { latitude: 42.3650, longitude: -71.2580 }, url: new URL("https://www.brandeis.edu/") }],
    ["Bryn Mawr College", { loc: { latitude: 40.0250, longitude: -75.3160 }, url: new URL("https://www.brynmawr.edu/") }],
    ["Bucknell University", { loc: { latitude: 40.9545, longitude: -76.8840 }, url: new URL("https://www.bucknell.edu/") }],
    ["California Polytechnic State University, San Luis Obispo", { loc: { latitude: 35.3050, longitude: -120.6625 }, url: new URL("https://www.calpoly.edu/") }],
    ["Carleton College", { loc: { latitude: 44.4600, longitude: -93.1530 }, url: new URL("https://www.carleton.edu/") }],
    ["Case Western Reserve University", { loc: { latitude: 41.5010, longitude: -81.6070 }, url: new URL("https://case.edu/") }],
    ["Claremont McKenna College", { loc: { latitude: 34.1020, longitude: -117.7070 }, url: new URL("https://www.cmc.edu/") }],
    ["Colby College", { loc: { latitude: 44.5650, longitude: -69.6620 }, url: new URL("https://www.colby.edu/") }],
    ["Colgate University", { loc: { latitude: 42.8180, longitude: -75.5400 }, url: new URL("https://www.colgate.edu/") }],
    ["College of the Holy Cross", { loc: { latitude: 42.2390, longitude: -71.8100 }, url: new URL("https://www.holycross.edu/") }],
    ["College of William & Mary", { loc: { latitude: 37.2707, longitude: -76.7090 }, url: new URL("https://www.wm.edu/") }],
    ["Colorado College", { loc: { latitude: 38.8462, longitude: -104.8260 }, url: new URL("https://www.coloradocollege.edu/") }],
    ["Connecticut College", { loc: { latitude: 41.3780, longitude: -72.1060 }, url: new URL("https://www.conncoll.edu/") }],
    ["Davidson College", { loc: { latitude: 35.5000, longitude: -80.8480 }, url: new URL("https://www.davidson.edu/") }],
    ["DePauw University", { loc: { latitude: 39.6400, longitude: -86.8610 }, url: new URL("https://www.depauw.edu/") }],
    ["Dickinson College", { loc: { latitude: 40.2020, longitude: -77.2000 }, url: new URL("https://www.dickinson.edu/") }],
    ["Drexel University", { loc: { latitude: 39.9566, longitude: -75.1899 }, url: new URL("https://drexel.edu/") }],
    ["Earlham College", { loc: { latitude: 39.8260, longitude: -84.9030 }, url: new URL("https://earlham.edu/") }],
    ["Elon University", { loc: { latitude: 36.1020, longitude: -79.5020 }, url: new URL("https://www.elon.edu/") }],
    ["Emerson College", { loc: { latitude: 42.3520, longitude: -71.0650 }, url: new URL("https://www.emerson.edu/") }],
    ["Franklin & Marshall College", { loc: { latitude: 40.0470, longitude: -76.3160 }, url: new URL("https://www.fandm.edu/") }],
    ["Furman University", { loc: { latitude: 34.9240, longitude: -82.4380 }, url: new URL("https://www.furman.edu/") }],
    ["George Washington University", { loc: { latitude: 38.8990, longitude: -77.0470 }, url: new URL("https://www.gwu.edu/") }],
    ["Gettysburg College", { loc: { latitude: 39.8350, longitude: -77.2340 }, url: new URL("https://www.gettysburg.edu/") }],
    ["Grinnell College", { loc: { latitude: 41.7510, longitude: -92.7190 }, url: new URL("https://www.grinnell.edu/") }],
    ["Hamilton College", { loc: { latitude: 43.0500, longitude: -75.4060 }, url: new URL("https://www.hamilton.edu/") }],
    ["Harvey Mudd College", { loc: { latitude: 34.1060, longitude: -117.7100 }, url: new URL("https://www.hmc.edu/") }],
    ["Haverford College", { loc: { latitude: 40.0120, longitude: -75.3080 }, url: new URL("https://www.haverford.edu/") }],
    ["Hobart and William Smith Colleges", { loc: { latitude: 42.8590, longitude: -76.9850 }, url: new URL("https://www.hws.edu/") }],
    ["Illinois Institute of Technology", { loc: { latitude: 41.8340, longitude: -87.6270 }, url: new URL("https://www.iit.edu/") }],
    ["Ithaca College", { loc: { latitude: 42.4220, longitude: -76.4940 }, url: new URL("https://www.ithaca.edu/") }],
    ["Kenyon College", { loc: { latitude: 40.3750, longitude: -82.3960 }, url: new URL("https://www.kenyon.edu/") }],
    ["Lafayette College", { loc: { latitude: 40.7000, longitude: -75.2090 }, url: new URL("https://www.lafayette.edu/") }],
    ["Lawrence University", { loc: { latitude: 44.2610, longitude: -88.4010 }, url: new URL("https://www.lawrence.edu/") }],
    ["Lehigh University", { loc: { latitude: 40.6060, longitude: -75.3780 }, url: new URL("https://www1.lehigh.edu/") }],
    ["Macalester College", { loc: { latitude: 44.9390, longitude: -93.1680 }, url: new URL("https://www.macalester.edu/") }],
    ["Middlebury College", { loc: { latitude: 44.0100, longitude: -73.1770 }, url: new URL("https://www.middlebury.edu/") }],
    ["Mount Holyoke College", { loc: { latitude: 42.2550, longitude: -72.5750 }, url: new URL("https://www.mtholyoke.edu/") }],
    ["Northeastern University", { loc: { latitude: 42.3390, longitude: -71.0890 }, url: new URL("https://www.northeastern.edu/") }],
    ["Oberlin College", { loc: { latitude: 41.2930, longitude: -82.2170 }, url: new URL("https://www.oberlin.edu/") }],
    ["Occidental College", { loc: { latitude: 34.1260, longitude: -118.2110 }, url: new URL("https://www.oxy.edu/") }],
    ["Pitzer College", { loc: { latitude: 34.1050, longitude: -117.7100 }, url: new URL("https://www.pitzer.edu/") }],
    ["Pomona College", { loc: { latitude: 34.0970, longitude: -117.7110 }, url: new URL("https://www.pomona.edu/") }],
    ["Reed College", { loc: { latitude: 45.4810, longitude: -122.6300 }, url: new URL("https://www.reed.edu/") }],
    ["Rensselaer Polytechnic Institute", { loc: { latitude: 42.7300, longitude: -73.6780 }, url: new URL("https://www.rpi.edu/") }],
    ["Rhodes College", { loc: { latitude: 35.1550, longitude: -89.9900 }, url: new URL("https://www.rhodes.edu/") }],
    ["Scripps College", { loc: { latitude: 34.1030, longitude: -117.7100 }, url: new URL("https://www.scrippscollege.edu/") }],
    ["Skidmore College", { loc: { latitude: 43.0960, longitude: -73.7840 }, url: new URL("https://www.skidmore.edu/") }],
    ["Smith College", { loc: { latitude: 42.3180, longitude: -72.6400 }, url: new URL("https://www.smith.edu/") }],
    ["St. Lawrence University", { loc: { latitude: 44.5900, longitude: -75.1620 }, url: new URL("https://www.stlawu.edu/") }],
    ["Swarthmore College", { loc: { latitude: 39.9060, longitude: -75.3550 }, url: new URL("https://www.swarthmore.edu/") }],
    ["Trinity College", { loc: { latitude: 41.7470, longitude: -72.6900 }, url: new URL("https://www.trincoll.edu/") }],
    ["Georgia Institute of Technology", { loc: { latitude: 33.7756, longitude: -84.3963 }, url: new URL("https://www.gatech.edu/") }],
    ["University of California, Davis", { loc: { latitude: 38.5382, longitude: -121.7617 }, url: new URL("https://www.ucdavis.edu/") }],
    ["University of California, Santa Cruz", { loc: { latitude: 36.9916, longitude: -122.0583 }, url: new URL("https://www.ucsc.edu/") }],
    ["University of California, Riverside", { loc: { latitude: 33.9737, longitude: -117.3281 }, url: new URL("https://www.ucr.edu/") }],
    ["University of Arizona", { loc: { latitude: 32.2319, longitude: -110.9501 }, url: new URL("https://www.arizona.edu/") }],
    ["Arizona State University", { loc: { latitude: 33.4242, longitude: -111.9281 }, url: new URL("https://www.asu.edu/") }],
    ["Rutgers University–New Brunswick", { loc: { latitude: 40.5000, longitude: -74.4474 }, url: new URL("https://www.rutgers.edu/") }],
    ["University of Kansas", { loc: { latitude: 38.9597, longitude: -95.2449 }, url: new URL("https://www.ku.edu/") }],
    ["University of Nebraska–Lincoln", { loc: { latitude: 40.8200, longitude: -96.7005 }, url: new URL("https://www.unl.edu/") }],
    ["University of Kentucky", { loc: { latitude: 38.0317, longitude: -84.5037 }, url: new URL("https://www.uky.edu/") }],
    ["University of Cincinnati", { loc: { latitude: 39.1317, longitude: -84.5155 }, url: new URL("https://www.uc.edu/") }],
    ["University of Illinois at Chicago", { loc: { latitude: 41.8715, longitude: -87.6498 }, url: new URL("https://www.uic.edu/") }],
    ["University of Texas at Dallas", { loc: { latitude: 32.9858, longitude: -96.7501 }, url: new URL("https://www.utdallas.edu/") }],
    ["Stony Brook University (SUNY)", { loc: { latitude: 40.9120, longitude: -73.1237 }, url: new URL("https://www.stonybrook.edu/") }],
    ["University of Alabama", { loc: { latitude: 33.2098, longitude: -87.5413 }, url: new URL("https://www.ua.edu/") }],
    ["Auburn University", { loc: { latitude: 32.6036, longitude: -85.4866 }, url: new URL("https://www.auburn.edu/") }],
    ["George Mason University", { loc: { latitude: 38.8323, longitude: -77.3097 }, url: new URL("https://www.gmu.edu/") }],
    ["University of Colorado Denver", { loc: { latitude: 39.7456, longitude: -105.0055 }, url: new URL("https://www.ucdenver.edu/") }],
    ["Kansas State University", { loc: { latitude: 39.1911, longitude: -96.5805 }, url: new URL("https://www.k-state.edu/") }],
    ["Oklahoma State University", { loc: { latitude: 36.1257, longitude: -97.0663 }, url: new URL("https://go.okstate.edu/") }],
    ["Vassar College", { loc: { latitude: 41.6869, longitude: -73.8966 }, url: new URL("https://www.vassar.edu/") }],
    ["Sarah Lawrence College", { loc: { latitude: 40.9350, longitude: -73.8431 }, url: new URL("https://www.sarahlawrence.edu/") }],
    ["College of Wooster", { loc: { latitude: 40.8106, longitude: -81.9368 }, url: new URL("https://www.wooster.edu/") }],
    ["Wheaton College (IL)", { loc: { latitude: 41.8661, longitude: -88.1070 }, url: new URL("https://www.wheaton.edu/") }],
    ["Denison University", { loc: { latitude: 40.0748, longitude: -82.5209 }, url: new URL("https://denison.edu/") }],
    ["Sewanee–The University of the South", { loc: { latitude: 35.2037, longitude: -85.9211 }, url: new URL("https://new.sewanee.edu/") }],
    ["Gustavus Adolphus College", { loc: { latitude: 44.3248, longitude: -93.9703 }, url: new URL("https://gustavus.edu/") }],
    ["St. Olaf College", { loc: { latitude: 44.4599, longitude: -93.1685 }, url: new URL("https://wp.stolaf.edu/") }],
    ["Lewis & Clark College", { loc: { latitude: 45.4500, longitude: -122.6700 }, url: new URL("https://www.lclark.edu/") }],
    ["Hendrix College", { loc: { latitude: 35.0990, longitude: -92.4428 }, url: new URL("https://www.hendrix.edu/") }],
    ["University of South Florida", { loc: { latitude: 28.0587, longitude: -82.4139 }, url: new URL("https://www.usf.edu/") }],
    ["Texas Tech University", { loc: { latitude: 33.5843, longitude: -101.8783 }, url: new URL("https://www.ttu.edu/") }],
    ["University of Houston", { loc: { latitude: 29.7199, longitude: -95.3422 }, url: new URL("https://www.uh.edu/") }],
    ["Florida International University", { loc: { latitude: 25.7560, longitude: -80.3749 }, url: new URL("https://www.fiu.edu/") }],
    ["Temple University", { loc: { latitude: 39.9810, longitude: -75.1555 }, url: new URL("https://www.temple.edu/") }],
    ["Loyola University Chicago", { loc: { latitude: 41.9995, longitude: -87.6583 }, url: new URL("https://www.luc.edu/") }],
    ["Seton Hall University", { loc: { latitude: 40.7429, longitude: -74.2465 }, url: new URL("https://www.shu.edu/") }],
    ["University of New Hampshire", { loc: { latitude: 43.1389, longitude: -70.9331 }, url: new URL("https://www.unh.edu/") }],
    ["University of Rhode Island", { loc: { latitude: 41.4862, longitude: -71.5290 }, url: new URL("https://www.uri.edu/") }],
    ["University of Maine", { loc: { latitude: 44.8980, longitude: -68.6671 }, url: new URL("https://umaine.edu/") }],
]);
